name: Build Nightly 12.3
run-name: Version 12.3.${{ github.run_number }}

on: workflow_dispatch

permissions:
  contents: read
  packages: read

jobs:
  build-nightly:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          dotnet restore

      - name: define env variables
        run: |
          echo "APP_VERSION=12.3.${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        run: |
          rake "update_go_license[ApplicationStartup.cs, ${{ secrets.GO_DIAGRAM_KEY }}]"
          dotnet build /p:Version=${{env.APP_VERSION}}

      - name : Test
        run: dotnet test -v normal --no-build  --logger:"html;LogFileName=${{ github.workspace }}/testLog_Windows.html"

      - name: Push test log as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testLog_Windows
          path: ./testLog*.html

